// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvrceukiwbbswrqrakek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2cmNldWtpd2Jic3dycXJha2VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MjMzODgsImV4cCI6MjA3ODE5OTM4OH0.td2IX7WT5p9vTQjpDK_x45F-X_ihxLU7sSVcf8RZkvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});